apiVersion: 1

datasources:
  - name: Loki Local
    uid: loki-${LOKI_TENANT}
    type: loki
    access: proxy
    url: $LOKI_URL
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: '$LOKI_TENANT'
